### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by CompleXashY** [lllk140/BilibiliLogin#2]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\BilibiliLogin-main\main.py", line 1, in <module>
    from application.apps.app import App
  File "C:\Users\Administrator\Desktop\BilibiliLogin-main\application\apps\app.py", line 3, in <module>
    from application.net.utils import get_versions
  File "C:\Users\Administrator\Desktop\BilibiliLogin-main\application\net\utils.py", line 2, in <module>
    from application.config import default_net_config
  File "C:\Users\Administrator\Desktop\BilibiliLogin-main\application\config.py", line 1, in <module>
    from application.utils import reader
  File "C:\Users\Administrator\Desktop\BilibiliLogin-main\application\utils.py", line 10, in <module>
    import rsa
ModuleNotFoundError: No module named 'rsa'

**Comment by lllk140** [comment]
> Traceback (most recent call last): File "C:\Users\Administrator\Desktop\BilibiliLogin-main\main.py", line 1, in from application.apps.app import App File "C:\Users\Administrator\Desktop\BilibiliLogin-main\application\apps\app.py", line 3, in from application.net.utils import get_versions File "C:\Users\Administrator\Desktop\BilibiliLogin-main\application\net\utils.py", line 2, in from application.config import default_net_config File "C:\Users\Administrator\Desktop\BilibiliLogin-main\application\config.py", line 1, in from application.utils import reader File "C:\Users\Administrator\Desktop\BilibiliLogin-main\application\utils.py", line 10, in import rsa ModuleNotFoundError: No module named 'rsa'

安装rsa库 pip install rsa

**Comment by CompleXashY** [comment]
奥！谢谢大佬

**Comment by CompleXashY** [comment]
登录时报错‘NoneType’object has no attribute 'josn'

**Comment by lllk140** [comment]
> 登录时报错‘NoneType’object has no attribute 'josn'

哪一步👀

**Comment by CompleXashY** [comment]
短信验证发送和账密登录后报错

**Comment by lllk140** [comment]
> 短信验证发送和账密登录后报错

👀人机验证后？我自己测半天都没啥问题
